spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 50MB
server:
  port: 8000
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  default-produces-media-type: application/json
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 8640000
logging:
  level:
    root: info