spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
  #    database: postgresql
  #    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 50MB
server:
  port: 8000
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  default-produces-media-type: application/json
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:fca579b54ebada72e31490a43cac0fa5b624655c8170519b861eb3f7221f4e57}
      expiration: 8640000
logging:
  level:
    root: info